# Generated by Django 5.1.1 on 2024-10-01 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Distributor',
        ),
        migrations.RenameField(
            model_name='distributor',
            old_name='question_text',
            new_name='track',
        ),
    ]
