# Generated by Django 5.1.1 on 2024-10-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0002_rename_question_distributor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='returns',
            field=models.CharField(default=12, max_length=200),
        ),
    ]
