# Generated by Django 5.1.1 on 2024-10-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0003_distributor_returns'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('date_received', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
