# Generated by Django 5.1.1 on 2024-10-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drug', '0004_createorder_delete_choice_delete_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateOrder',
        ),
    ]
